### PR TITLE
fix: stopping search not working

### LINKED ISSUE #276: [BUG] stopping chat search takes ages
### Description

How to reproduce: login, start a search, stop it

You will notice it just doesn't stop at all

### Screenshots

image

### Additional information

_No response_

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by Dun-sin**
# Fixes Issue

**My PR closes #276**

# 👨‍💻 Changes proposed(What did you do ?)
- called the function that's responsible for stopping search

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

### CODE REVIEW

File: client/src/components/BuddyMatcher.jsx [hunk 1]
```diff
@@ -139,6 +139,7 @@ const BuddyMatcher = () => {
         });
 
         socket.on('stop_search_success', () => {
+            console.log('stopping search stop socket')
```
Comment (Dun-sin) [inline client/src/components/BuddyMatcher.jsx:142]:
```suggestion
```
