### PR TITLE
fix: properly restore chats

### LINKED ISSUE #595: [BUG] Chat isn't being restored properly
### Description

chat restore event is only being listened to in `anonymous` page, which isn't working properly. It has to be listened to at a higher level so that chats are restored no matter the page the user is on.

### Screenshots

_No response_

### Additional information

_No response_

### 🥦 Browser

Other

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by mathiasayivor**
# Fixes Issue

**My PR closes #595**

# 👨‍💻 Changes proposed(What did you do ?)
* Chats are now properly restored no matter the page the user is currently on
# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

## Note to reviewers

# 📷 Screenshots

### CODE REVIEW

File: src/components/PageWrapper.tsx
Comment (Dun-sin) [inline src/components/PageWrapper.tsx:1]: what's the logic behind the restore being done here?

File: src/pages/searching.tsx [hunk 1]
```diff
@@ -98,6 +98,14 @@ const Searching = () => {
     };
   }, [app.currentChatId, authState.email, authState.loginId, router, socket]);
 
+  useEffect(() => {
+    if (!app.currentChatId) {
+      return;
+    }
+
+    router.push('/anonymous')
```
Comment (Dun-sin) [inline src/pages/searching.tsx:106]: This could cause a problem tho, why not just let the user go back themselves by clicking a button like we previously did

**Review by Dun-sin — CHANGES_REQUESTED** [review]

File: src/pages/searching.tsx (hunk 1 above)
Comment (mathiasayivor) [reply src/pages/searching.tsx:106]: Because when the chat is restored, `searching` page does not stop the animation and the user does not have access to the chat interface. They never know when the chat is restored.

File: src/components/PageWrapper.tsx
Comment (mathiasayivor) [reply src/components/PageWrapper.tsx:1]: Currently, chat restoration only works on `anonymous` page, which means even if the chat restore event is received and the user is on `searching` or any other page, it doesn't get handled. So, by moving the handler here, we are guaranteed that chat is always restored no matter the page the user is currently on.

Comment (Dun-sin) [reply src/components/PageWrapper.tsx:1]: got it, perfect reasoning

File: src/pages/searching.tsx (hunk 1 above)
Comment (Dun-sin) [reply src/pages/searching.tsx:106]: hold up, this is to work when the user is already searching and not before? I think before is best right?

Comment (Dun-sin) [reply src/pages/searching.tsx:106]: yep, that's the flow

you're saying even if the user is on the homepage, it redirects back?

Comment (mathiasayivor) [reply src/pages/searching.tsx:106]: > you're saying even if the user is on the homepage, it redirects back?

No. User gets redirected only if they're on `/searching`

Comment (Dun-sin) [reply src/pages/searching.tsx:106]: I think it's better if we:
- check if the user has a chatid and prevent them from going to the searching page in general
- only redirect them outside of the chat page

Comment (mathiasayivor) [reply src/pages/searching.tsx:106]: I think we're already doing that.
There's no better place to redirect users from `searching` page than `searching` page itself. We could use a middleware, but it seems middlewares in Next only run on server, so checking for the currentChat Id is quite tricky due to our current structure.

Comment (Dun-sin) [reply src/pages/searching.tsx:106]: it's in the context no?

Comment (Dun-sin) [reply src/pages/searching.tsx:106]: but i also think both places should have it, the first one to check in the home page and the second to check in the searching page.

You said the first one is done already right?

Comment (mathiasayivor) [reply src/pages/searching.tsx:106]: Second one is already done.

But, is the the first not going to disturb? I mean we could display other stuff there instead of just redirecting.

Comment (Dun-sin) [reply src/pages/searching.tsx:106]: I think the first way is dome the so nevermind actually

**Review by Dun-sin — APPROVED** [review]
