### PR TITLE
fix: Reply chat text not show

### LINKED ISSUE #631: [BUG] Reply chat text not show
### Description

The reply chat text is not showing.

### Screenshots

whisperreply

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Golu7667**
# Fixes Issue

**My PR closes #631**

# 👨‍💻 Changes proposed(What did you do ?)
The replyTo ID is passed to the getRepliedMessage function. This ID is used to search within the decryptedMessages array, which already contains the decrypted messages. The function finds the message object that matches the replyTo, ID and returns it.everything is working fine.

# ✔️ Check List (Check all the applicable boxes)

- [1] My code follows the code style of this project.
- [2] This PR does not contain plagiarized content.
- [3] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

whisperreply

### CODE REVIEW

File: client/src/components/Chat.jsx [hunk 1]
```diff
@@ -258,6 +258,10 @@ const Chat = () => {
 	const showBadword = (id) => {
 		setBadwordChoices({ ...badwordChoices, [id]: 'show' });
 	};
+ 
+	function getRepliedMessage(replyTo){
+		return decryptedMessages.find(object=>object.id===replyTo)
+	}
```
Comment (Dun-sin) [inline client/src/components/Chat.jsx:264]: Pls run ESLint on this file or install ESLint VS Code extension

**Review by Dun-sin — CHANGES_REQUESTED** [review]

File: client/src/components/Chat.jsx (hunk 1 above)
Comment (Golu7667) [reply client/src/components/Chat.jsx]: I use Prettier to format the code in this file.

**Review by Dun-sin — APPROVED** [review]
thanks, looks good
