### PR TITLE
fix: Copying chat not work

### LINKED ISSUE #628: [BUG] Copying chat not work
### Description

When I copy chat, it is not copying correctly.

### Screenshots

whispercopy

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Golu7667**
# Fixes Issue

**My PR closes #628**

# 👨‍💻 Changes proposed(What did you do ?)
Send cryptoKey and importedPrivateKey to chatHelper. The message is encrypted and then decrypted using the decryptMessage function with the key (cryptoKey, importedPrivateKey). After decryption, copying text works correctly.

# ✔️ Check List (Check all the applicable boxes)

- [1] My code follows the code style of this project.
- [2] This PR does not contain plagiarized content.
- [3] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

whispercopyworking

### CODE REVIEW

**Comment by Golu7667** [comment]
@dunsin review my pr and merge this

**Comment by Dun-sin** [comment]
> @dunsin review my pr and merge this 

keep in mind in the future you don't need to comment back on the Issue, you can after 5 days, it's not my first rodeo, so I see your PR and will definitely do what's needed to be done. It will just cause unnecessary notifications for me and others.

File: client/src/components/Chat.jsx [hunk 1]
```diff
@@ -535,6 +535,8 @@ const Chat = () => {
 																cancelEdit={cancelEdit}
 																setEditing={setEditing}
 																setReplyId={startReply}
+																cryptoKey={cryptoKey}
+																importedPrivateKey={importedPrivateKey}
```
Comment (Dun-sin) [inline client/src/components/Chat.jsx:539]: No need to pass it down, it's a Hook that can be imported in the dropdownoption component.

Here: https://github.com/Dun-sin/Whisper/blob/c6f0687bbb759262e99d23e8ffb40eb0ca9c6afd/client/src/hooks/useCryptoKeys.js#L8

So just import it and then use the needed functions

Like this: https://github.com/Dun-sin/Whisper/blob/c6f0687bbb759262e99d23e8ffb40eb0ca9c6afd/client/src/components/Chat.jsx#L70

File: client/src/components/Chat/DropDownOption.jsx [hunk 2]
```diff
@@ -12,9 +12,9 @@ import { socket } from 'src/lib/socketConnection';
 
 import useChatUtils from 'src/lib/chatSocket';
 
-const DropDownOptions = ({ id, isSender, inputRef, cancelEdit, setEditing, setReplyId }) => {
+const DropDownOptions = ({ id, isSender, inputRef, cancelEdit, setEditing, setReplyId ,cryptoKey,importedPrivateKey}) => {
 	const { app } = useApp();
-
+  
 	const { messages: state, updateMessage, removeMessage } = useChat();
```
Comment (Dun-sin) [inline client/src/components/Chat/DropDownOption.jsx:18]: So that means you use the hook hear and remove the passing down

File: client/src/lib/chatHelper.js [hunk 3]
```diff
@@ -27,15 +29,16 @@ export default (state, app) => {
 		});
 	};
 
-	const handleCopyToClipBoard = async (id) => {
+	const handleCopyToClipBoard = async (id,state, app,key) => {
```
Comment (Dun-sin) [inline client/src/lib/chatHelper.js:32]: Remove the parameter definition, because we already did it here: https://github.com/Dun-sin/Whisper/blob/c6f0687bbb759262e99d23e8ffb40eb0ca9c6afd/client/src/lib/chatHelper.js#L1

The function is inside a function that has those two parameters defined

**Review by Dun-sin — CHANGES_REQUESTED** [review]

File: client/src/components/Chat/DropDownOption.jsx (hunk 2 above)
Comment (Golu7667) [reply client/src/components/Chat/DropDownOption.jsx:18]: In DropDownOption.jsx, when I use the hook useCryptoKeys, the values importedPrivateKey and cryptoKey are showing as null
whispercopy02
whispercopy03

Comment (Golu7667) [reply client/src/components/Chat/DropDownOption.jsx:18]: "The importedPublicKey, importedPrivateKey, and cryptoKey are all null because the hook is not implemented correctly. If you give me permission, I can resolve this issue. whispergenerate
In the chat.jsx file, the keys are retrieved because the generateKeyPair() function is available. If generateKeyPair() is not available, the keys cannot be retrieved.
whispergenerate02

Comment (Dun-sin) [reply client/src/components/Chat/DropDownOption.jsx:18]: Sure

File: client/src/App.jsx
Comment (Dun-sin) [inline client/src/App.jsx:1]: remove the change from this file

File: client/src/components/Chat/DropDownOption.jsx [hunk 4]
```diff
@@ -120,4 +124,6 @@ DropDownOptions.propTypes = {
 	cancelEdit: PropTypes.func.isRequired,
 	setEditing: PropTypes.func.isRequired,
 	setReplyId: PropTypes.func.isRequired,
+	cryptoKey:PropTypes.object.isRequired,
+	importedPrivateKey:PropTypes.object.isRequired
```
Comment (Dun-sin) [inline client/src/components/Chat/DropDownOption.jsx:128]: Remember you've changed your code back to not have this a a props

File: client/src/hooks/useCryptoKeys.js
Comment (Dun-sin) [inline client/src/hooks/useCryptoKeys.js:1]: Please explain your changes here

**Review by Dun-sin — CHANGES_REQUESTED** [review]

**Comment by Dun-sin** [comment]
@Golu7667 stiil interested in this?

File: client/src/hooks/useCryptoKeys.js
Comment (Golu7667) [reply client/src/hooks/useCryptoKeys.js:1]: CryptoKey, importPublicKey, and importedPrivateKey are present in local storage and are retrieved and stored into storedCryptoKey, storedPublicKey, and storedPrivateKey. Then, using useEffect, the keys are converted into Uint8Array objects and stored. in old code This process happens when generateKeyPair is called, which is why the key is null initially, but right now this is working fine.

Comment (Dun-sin) [reply client/src/hooks/useCryptoKeys.js:1]: Good spot. Thanks for the explanation

**Review by Dun-sin — APPROVED** [review]
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star, sharing the project to your friends, and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

**Comment by Dun-sin** [comment]
actually @Golu7667 can you raise the PR again, and don't add app.jsx, your method of reverting the file is wrong as it deleted the original from the source code
