### PR TITLE
fix: Age Validation in Profile Section

### LINKED ISSUE #410: Add Age Validation in Profile Section
### Description

In the profile section's form, there is a label for "age", which allows users to update their age. However, currently, there is **no validation** in place, and **users can enter negative values**. To ensure data accuracy and consistency, we need to add age validation to ensure that **only positive values are accepted**.

### Screenshots

Screenshot 2023-10-13 at 1 55 22 PM
_Age shouldn't be negative._

### Additional information

- We should add client-side validation to prevent users from entering negative values for age. This can be achieved using HTML5 input attributes or JavaScript validation.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by varundhand**
# Fixes Issue #410 

**My PR closes #410**

# 👨‍💻 Changes proposed(What did you do ?)
I have implemented client-side validation to **prevent users** from entering **negative values for age**. This was achieved by using HTML attributes and JavaScript validation.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers
Could you please consider adding the "hacktoberfest" and "hacktoberfest-accepted" labels to this pr? Thanks a bunch!

# 📷 Screenshots

https://github.com/Dun-sin/Whisper/assets/110025628/7ce43ebb-90fa-4309-a17c-4b765a21b7ff

### CODE REVIEW

**Comment by Dun-sin** [comment]
> @Dun-sin ready for review

Please don't tag maintainers for a review, we see the PR you create.

File: client/src/pages/Profile.jsx [hunk 1]
```diff
@@ -139,6 +139,12 @@ const Profile = () => {
                                         placeholder="19"
                                         className='outline-none bg-transparent text-right'
                                         ref={ageRef}
+                                        min="1"
+                                        onBlur={(e) => {
```
Comment (Dun-sin) [inline client/src/pages/Profile.jsx:143]:
```suggestion
                                        onChange={(e) => {
```

**Review by Dun-sin — APPROVED** [review]
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)
