### PR TITLE
fix: Volume slider is unusable

### LINKED ISSUE #589: [BUG] Volume slider in settings has a width of 0
### Description

The volume slider has a width of 0 so it's unusable.

### Screenshots

image

### Additional information

It can be fixed by setting the width of the `div.rs-form-control-wrapper` wrapping the slider to 100%. There isn't an option to pass a class to that div as far as I know, so it will require custom CSS.

### 🥦 Browser

Other

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by benaissazaki**
# Fixes Issue

My PR closes #589 

# 👨‍💻 Changes proposed(What did you do ?)
The volume slider in the settings had a width of 0 which made it unusable. Now it takes 100% of the available width which is better.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

## Note to reviewers
/

# 📷 Screenshots

Before
image

After
image

### CODE REVIEW

File: src/pages/settings.tsx [hunk 1]
```diff
@@ -61,6 +61,11 @@ const Settings = () => {
     <div className='flex justify-center items-center flex-col min-w-[calc(100%-120px)] p-2 gap-5 bg-white dark:bg-primary min-h-full'>
       <div className='w-11/12 sm:w-[70%] md:w-[55%] lg:w-[35%] md:min-w-[300px] h-auto dark:bg-primary bg-light rounded-3xl px-6 py-6 md:px-14 md:py-20 border shadow-xl text-primary  dark:text-light '>
         <Form onSubmit={handleSubmit} onChange={handleChange}>
+          <style global jsx>{`
+            .rs-form-control {
+              width: 100%;
+            }
+          `}</style>
```
Comment (Dun-sin) [inline src/pages/settings.tsx:68]: this isn't clean, pls do it in the global.css file

**Review by Dun-sin — CHANGES_REQUESTED** [review]

**Review by Dun-sin — APPROVED** [review]
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)
