### PR TITLE
fix: Room not found

### LINKED ISSUE #577: [BUG] Room not found
### Description

Screenshot (207)

When I log in as an anonymous user and try to send a message, I encounter this error. Please let me know if there are any additional settings required. If not, I'd like to work on this issue.

### Screenshots

_No response_

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by MJinH**
# Fixes Issue

**My PR closes #577 **

# 👨‍💻 Changes proposed(What did you do ?)

1. commented out the lines in anonymous.tsx file. Had an issue where the socket would connect on the server side but immediately disconnect on the client side, which was causing the `NEW_EVENT_CHAT_RESTORE` event to not work properly.

2. After debugging, noticed that the `createChat` function wasn't being called properly in the anonymous.tsx file. suspect this was because it was being called before the provider was initialized, so wrapped the components with `ChatProvider` in the _app.tsx file and confirmed that it was working correctly.

# ✔️ Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

## Note to reviewers

# 📷 Screenshots

### CODE REVIEW

**Comment by Dun-sin** [comment]
Will review this later in the day @MJinH in the mean time, please remove the package files, don't delete them but remove them from your PR. Thanks

**Comment by Dun-sin** [comment]
Can't do that, deleting it from here is deleting it from the actual code, we don't want that.

You have to close this PR, and raise it again without the package files in it

**Review by Dun-sin — COMMENTED** [review]
Leave the naming

**Review by Dun-sin — CHANGES_REQUESTED** [review]
Please remove everything that doesn't have to do with the issue, like changing name or formatting?

Also why are you calling context twice as we've already called it in PageWrapper.tsx, so either you remove it from there and leave your changes or vice versa, but can't be both

**Comment by MJinH** [comment]
Could you please check this? in the ChatContext.tsx file, when the name is "chatId" in the createChat, it seems to result in 'undefined' in the chatReducer, causing a room not found error as shown in the image. When using 'id', it looks like it's assigned correctly. Please let me know if i missed something. Also, yes you're right. I forgot to remove the context in the PageWrapper.tsx file.  

Screenshot (211)


Screenshot (208)

**Comment by Dun-sin** [comment]
> Could you please check this? in the ChatContext.tsx file, when the name is "chatId" in the createChat, it seems to result in 'undefined' in the chatReducer as shown in the image. When using 'id', it looks like it's assigned correctly. Please let me know if i missed something. Also, yes you're right. I forgot to remove the context in the PageWrapper.tsx file.
> 
> Screenshot (211)
> 
> Screenshot (208)

i guess the issue comes from here:
remove the id and leave the chatId, should fix it, can't believe i missed that
https://github.com/Dun-sin/Whisper/blob/94b3b503ac05dd3d4cf6e9ad6250da494cead95c/src/reducer/chatReducer.ts#L24

**Comment by MJinH** [comment]
got it, and if the provider is in PageWrapper, the createChat in anonymous.tsx doesn't seem to be called properly. When debugging, it gets called as `createChat: () => {}` and exits immediately. can you please check this as well?

I'll fix those and recommit later. Thank you.

File: src/reducer/chatReducer.ts [hunk 1]
```diff
@@ -109,12 +109,14 @@ export default function chatReducer(state: ChatIdType, action: any) {
       }
       clonedState[room].messages[messageId].isEdited = message.isEdited;
 
-      if (oldMessages.length === 0) {
+      if (oldMessages) {
+        if (oldMessages.length === 0) {
+          break;
+        }
+
+        clonedState[room].messages[messageId].oldMessages = oldMessages;
```
Comment (Dun-sin) [inline src/reducer/chatReducer.ts:117]: remove this change

File: src/pages/api/server/index.ts
Comment (Dun-sin) [inline src/pages/api/server/index.ts:1]: remove this change as well

File: src/pages/anonymous.tsx
Comment (Dun-sin) [inline src/pages/anonymous.tsx:1]: here too

File: src/types/contextTypes.ts
Comment (Dun-sin) [inline src/types/contextTypes.ts:1]: here too

**Review by Dun-sin — CHANGES_REQUESTED** [review]

**Comment by Dun-sin** [comment]
Also @MJinH what exactly do you mean in Anonmyous.tsx?

**Comment by MJinH** [comment]
What I mean is, when ChatProvider is in PageWrapper, createChat is exeucted like this
[room-1.webm](https://github.com/Dun-sin/Whisper/assets/97130553/7e262612-3d39-4d67-b051-b362565c385d)



and this is when the provider is in _app.tsx
room-2

**Comment by Dun-sin** [comment]
> What I mean is, when ChatProvider is in PageWrapper, createChat is exeucted like this
> [room-1.webm](https://github.com/Dun-sin/Whisper/assets/97130553/7e262612-3d39-4d67-b051-b362565c385d)
> 
> 
> 
> and this is when the provider is in _app.tsx
> room-2
> 

I see your point, yours is a better way then💪🏽 but the other things still count

File: src/reducer/chatReducer.ts [hunk 2]
```diff
@@ -165,4 +165,4 @@ export default function chatReducer(state: ChatIdType, action: any) {
   localStorage.setItem('chats', JSON.stringify(clonedState));
 
   return clonedState;
-}
+}
```
Comment (Dun-sin) [inline src/reducer/chatReducer.ts:168]: Here too, I think there was also an empty line at the end instead

**Review by Dun-sin — CHANGES_REQUESTED** [review]

**Review by Dun-sin — APPROVED** [review]
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)
